apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aggregator-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: worker
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
