services:
 # Redis DB
  redis:
    image: redis:7-alpine
    container_name: redis_server
    command: redis-server --requirepass password@123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  #  RedisInsight Dashboard Service
  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    restart: always
 # Application end points
  api:
    build: .
    container_name: api_service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_URL=redis://:password@123@redis:6379
    depends_on:
      - redis
 # node workers
  worker:
    build: .
    container_name: worker_service
    command: npm run start:worker
    environment:
      - REDIS_URL=redis://:password@123@redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
