apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: production
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  API_PORT: "4001"
  AGGREGATOR_PORT: "4002"
  WORKER_PORT: "4003"
