apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: default
  labels:
    app: aggregator
spec:
  type: ClusterIP
  selector:
    app: aggregator
  ports:
    - name: metrics  # metrics scraping
      protocol: TCP
      port: 4002
      targetPort: 4002
