apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: my-app-service:latest
        imagePullPolicy: Never
        command: ["node", "dist/api.js"]
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 4001
