apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api # Must match the Deployment labels
  ports:
    - protocol: TCP
      port: 4001 # The port the service exposes
      targetPort: 4001 # The port the container is listening on
      nodePort: 30001 # External access port (accessible via localhost:30001)
  type: NodePort # Allows external traffic from outside the cluster
