apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: default
  labels:
    app: worker
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: metrics # Prometheus targets port
      protocol: TCP
      port: 4003
      targetPort: 4003
