apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: my-app-service:latest
        imagePullPolicy: Never
        command: ["npm", "run", "start:worker"]

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        ports:
        - containerPort: 4003

        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
