apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 4001 # Prometheus will scrape this service on port 4001
      targetPort: 4001
  type: ClusterIP # Only internal access needed for metrics scraping
